language: scala

scala:
- 2.11.6

jdk:
- oraclejdk7

notifications:
  webhooks:
	  urls:
		- https://webhooks.gitter.im/e/594eb7b7f47c0f81753e
	  on_success: change
	  on_failure: always
	  on_start: false

branches:
  only:
  - master
  - dev